sudo: required
language: python
python:
  - 3.5.2
install:
  - pip install -r requirements.txt
  - cd term
script:
  - coverage run -m --branch --omit=test_*,*/lib/* --source=. unittest discover
after_success:
  - coveralls
